### ISSUE TITLE
Unshare ocm notification is not handled for ocm-group (old caption: there is a syntax error in federatedGroups/OcmController)

### ISSUE THREAD

**Issue by soltanireza65** [SURFnet/rd-sram-integration#106]
the method signature asks for 3 args, but we are passing 2
whether update the method implementation and make 3rd one optional or if its necessary, pass the corresponding args

https://github.com/SURFnet/rd-sram-integration/blob/e49156345ed8ff7d5b16f0facf6f75176e3cd4f5/federatedgroups/lib/Controller/OcmController.php#L397

![image](https://user-images.githubusercontent.com/53468377/220416040-34322a18-8305-4e30-b2fb-6fa12a16832c.png)

**Comment by soltanireza65** [comment]
![image](https://user-images.githubusercontent.com/53468377/221890502-9cbf7cd3-4b0b-46d3-87d9-4de28be58233.png)
it has 3 implementations 
we should check which one to use

**Comment by soltanireza65** [comment]
since we have to pass shareType to the local FedShareManager to determine witch provider to use, 
so we should first get shareObject from ocmMiddleware, then pass its shareType to the unShare method.
https://github.com/SURFnet/rd-sram-integration/tree/fix/issue%23106

**Comment by soltanireza65** [comment]
but I need to know if getValidShare, works the way we expect in this case, (I didn't drill down)
since I did not simulate the case

**Comment by michielbdejong** [comment]
> we should check which one to use

It's the top one ("FedShareManager")

**Comment by michielbdejong** [comment]
The trouble is that [OCM notifications](https://cs3org.github.io/OCM-API/docs.html?branch=develop&repo=OCM-API&user=cs3org#/paths/~1notifications/post) don't include the `shareType` from the OCM share call they refer to, only the `shareId`.  So I think we need to encode `shareType` 'group' vs 'user' into the `shareId` when we send a share. Historically, shares of type 'user' will have been sent already with just the db id as their shareId, so maybe we should e.g. prefix the shareId with `g_` in case of `shareType` 'group' and with nothing in case of `shareType` 'user'.

**Comment by michielbdejong** [comment]
And then when processing the `NOTIFICATION_TYPE_SHARE_UNSHARED` we should unpack that `remoteId` into a shareType (prefix `g_` present or not?) and a db id.

**Comment by navid-shokri** [comment]
Interesting, according to this page: 

https://cs3org.github.io/OCM-API/docs.html?branch=develop&repo=OCM-API&user=cs3org#/paths/~1notifications/post

there is a `notification` parameter which is an object type and maybe we can use it temporarily

**Comment by navid-shokri** [comment]
I found another problem there. so on sender side when I am trying to unshare a file we are getting this error : 
 > Wrong share ID, share doesn\'t exist

**Comment by navid-shokri** [comment]
So I modified some files on CORE repository you find them on :information_source: 

https://github.com/pondersource/core/pull/new/unshare-bugfix

and my changes on this repository 
https://github.com/SURFnet/rd-sram-integration/pull/new/fic%23106
BUT there is another part of code that should be done

**Comment by navid-shokri** [comment]
THE PROBLEM: :boom: 

*FederatedFileSharing->processNotification` is using `OCA\FederatedFileSharing\FedShareManager` to process all types of notifications. 
So, We splitted the FedShareManager for the FederatedGroup app, So we need to access both FedShareManagers in the OcmController.
but I did not figure out how to do that without damaging the main design.
NOTE: :bell: 
# Notification types are: 
- NOTIFICATION_TYPE_SHARE_ACCEPTED
- NOTIFICATION_TYPE_SHARE_DECLINED
- NOTIFICATION_TYPE_REQUEST_RESHARE
- NOTIFICATION_TYPE_RESHARE_CHANGE_PERMISSION
- NOTIFICATION_TYPE_SHARE_UNSHARED
- NOTIFICATION_TYPE_RESHARE_UNDO (UNSUPPORTED) :red_circle:

**Comment by michielbdejong** [comment]
There are a few options:
1) change the FedShareManager of the FederatedFileSharing app to support not just notifications about user-to-user but also  about user-to-group share. This option has been rejected by the maintainers of ownCloud core.
2) add a switch  at the entry point of FederatedFileSharing->processNotification that checks the config to see whether an OCM notification handler is explicitly configured, and if so, find that handler in the DI container, and switch to that.
3) add a lookup at the entry point of FederatedFileSharing->processNotification that tries to find the share in both tables, and depending on the result, picks a code path (stay in FederatedFileSharing for user-to-user or use the mechanism from 2) to switch to our new OpenCloudMesh app for processing notifications about user-to-group shares if configured).


I think option 3 would not work because
- the switching code would already rely on the database table that might not exist
- it's clunky to have two almost identical code paths alive side-by-side and switch between them on a per-request basis.

So let's pick option 2.

Then the next question is how should the FedShareManager of the OpenCloudMesh app depend on the FedShareManager of the FederatedFileSharing app. Options:
1) copy and edit it
2) inherit from it
3) copy it and clean it up to allow easier inheritance (e.g. change `private` to `protected` where appropriate), and then proceed to inherit from it.

I think from what I've seen in other parts of the code base, option 3 is probably cleanest?

@navid-shokri and @yasharpm you can use this as guidance and discuss it with each other to get this resolved in a way that works and that is also maintainable. Good luck!

**Comment by michielbdejong** [comment]
We have agreement to pick option 2 for question 1.

**Comment by michielbdejong** [comment]
For second question option 3, we can use one base class that has all the code in it, and then inherit one tiny child class for user-to-user and another one for user-to-group.

**Comment by michielbdejong** [comment]
After a long discussion we also have agreement on option 3 for question 2.
