### ISSUE TITLE
make things 'protected' in surf-dev branch

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#111]
All these private class properties: https://github.com/pondersource/core/blob/surf-dev/apps/federatedfilesharing/lib/FederatedShareProvider.php#L53-L86
And functions like https://github.com/pondersource/core/blob/surf-dev/apps/federatedfilesharing/lib/FederatedShareProvider.php#L931 should just be 'protected' instead of 'private' in the surf-dev branch

**Comment by michielbdejong** [comment]
And then we can get rid of the overwriting private variables in the child class, like https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedGroupShareProvider.php#L116-L117

**Comment by navid-shokri** [comment]
there is no certainty that we could do such action or not because as mentioned in the meeting with the `core` developer we were just allowed to copy the existing code and modify the duplicated files. 
also, the subsequence of such action may be difficult to deal with. in the last refactor that we perform all of the already finished parts were affected and it create a ton of subsidiary changes.

**Comment by michielbdejong** [comment]
I think this was done.
