### ISSUE TITLE
remove unused variable

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#112]
this is not used and shouldn't be there: https://github.com/SURFnet/rd-sram-integration/blob/main/federatedgroups/lib/FederatedGroupShareProvider.php#L58

**Comment by soltanireza65** [comment]
https://github.com/SURFnet/rd-sram-integration/tree/fix/issue%23112

since it's 'private' and not used in class, it can be removed with confidence

**Comment by soltanireza65** [comment]
there is another issue with this file:

https://github.com/SURFnet/rd-sram-integration/blob/a29acae54af74d5ce0a790fb728da869dc90aff9/federatedgroups/lib/FederatedGroupShareProvider.php#L116

we are initializing $notifications in the constructor, while we don't have a class property called $notifications
since we haven't called it in class, let me know if we should remove initialization, or add a class field (this is probably the case)

**Comment by soltanireza65** [comment]
https://github.com/SURFnet/rd-sram-integration/blob/a29acae54af74d5ce0a790fb728da869dc90aff9/federatedgroups/lib/FederatedGroupShareProvider.php#L152

also this one

**Comment by soltanireza65** [comment]
https://github.com/SURFnet/rd-sram-integration/blob/a29acae54af74d5ce0a790fb728da869dc90aff9/federatedgroups/lib/FederatedGroupShareProvider.php#L190

also this one

**Comment by soltanireza65** [comment]
i have checked that either class or its direct parents should have these fields

**Comment by navid-shokri** [comment]
@soltanireza65, please create a branch from the main and merge it with fix/issue#93 and then continue your task.

**Comment by soltanireza65** [comment]
> @soltanireza65, please create a branch from the main and merge it with fix/issue#93 and then continue your task.

I have checked out the https://github.com/SURFnet/rd-sram-integration/tree/fix/issue%23112 
from the main branch already

**Comment by soltanireza65** [comment]
added class field $notifications to https://github.com/SURFnet/rd-sram-integration/blob/39d8ab80c37db2458652d1f7810f91a1b3b0741f/federatedgroups/lib/FederatedGroupShareProvider.php#L62
