### ISSUE TITLE
handling OCM notifications on the sender side across multiple share providers

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#132]
When a notification arrives at the sender side, which component handles the db lookup?

Because I think in regular ownCloud that would be the FederatedShareProvider, but in our case the appropriate share provider could be either the FederatedShareProvider, or the FederatedGroupShareProvider, or the MixedGroupShareProvider, right?

But they would all do this lookup in oc_share, so it doesn't make sense to execute that db query 3 times.

@navid-dada any ideas about this?

Related to #106

**Comment by navid-shokri** [comment]
I think it will be federatedShareProvider. but there should not be any problem. because on sender host there is just working on oc_share. so if there is any flow that is trying to execute one query 3 time so it is wrong and we should fix it. But, I did not noticed such condition in code. if you have any please share it with me.

**Comment by michielbdejong** [comment]
Are you using X-Debug yet? If not, ask @MahdiBaghbani to show you.

Please step through it with X-Debug and confirm what path it takes and which methods of which classes it passes through from the http hit to the db hit, if you can.
