### ISSUE TITLE
Error on accepting the share

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#207]
![Image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/37edbd87-642e-4ebc-860b-dabf28b263f5)

**Comment by michielbdejong** [comment]
That's https://github.com/owncloud/core/blob/v10.12.2/apps/files_sharing/lib/Controller/RemoteOcsController.php#L99
I'll see if I can find out in which situation this could have happened

**Comment by michielbdejong** [comment]
Related to https://github.com/SURFnet/rd-sram-integration/issues/53

**Comment by michielbdejong** [comment]
I wasn't able to reproduce this with the latest version of our opencloudmesh app on dev-stock main branch.
I tried:
* Einstein removing the share before Marie accepts it
* Einstein removing the share after Marie displays the dialog but before Marie clicks
* deleting the share from the `oc_share` table on Einstein's side before Marie accepts it
* deleting the share from the `oc_share_external_group` table on Marie's side before Marie accepts it

This in itself is maybe also worrying, because you would expect to see some sort of error message if the share you're trying to accept was deleted! -> https://github.com/pondersource/oc-opencloudmesh/issues/23
