### ISSUE TITLE
share to mixed group not arriving

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#213]
* follow https://github.com/suRFnet/rd-sram-integration#testing-environment
* as einstein on oc1.docker, create a folder asdf and share it with 'test group ... '
<img width="1121" alt="Screenshot 2023-06-22 at 16 13 54" src="https://github.com/SURFnet/rd-sram-integration/assets/408412/326ddcc3-2b88-440e-a962-3acb4441bd2a">

* as marie on oc2.docker you'll see that no share arrived
<img width="1121" alt="Screenshot 2023-06-22 at 16 13 59" src="https://github.com/SURFnet/rd-sram-integration/assets/408412/beaa2a0f-9a75-416e-8363-6cc6c9293236">

**Comment by shokri-navid** [comment]
🤔
So why marie did not receive any share?

**Comment by michielbdejong** [comment]
if you were unable to reproduce this then let's do a screenshare session where i talk you through it!

**Comment by michielbdejong** [comment]
> I tested this happy scenario dozen times 

just to clarify, I ran into this bug with [this](https://github.com/pondersource/dev-stock/commit/af8b5f4ff8958a64c428c26987dfa18d3ade8582) version of the code which was published just 25 minutes before your comment. Maybe you are talking about a previous version of the code?

**Comment by michielbdejong** [comment]
where "previous" may also be a different branch of dev-stock, a different branch of the opencloudmesh app, a different branch of the federatedgroups app, or a different branch of owncloud/core. All these things influence it, so as we found this morning, we need to make sure we all use the same revision of the same fork! :)

**Comment by navid-shokri** [comment]
:information_source: 

So, I guess this image can prof my forecast but I will try to show more symptoms: 
![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/65e55b80-9206-4645-8b79-4cb2a85b2a3d)

As it is obvious in the above image marei is just a member of the admin group. So I will share the `init.sh` file with the `test group`:
![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/cd6841ec-91ed-4808-a8c9-69159dc0698a)

and yes Marie is not notified because she is not enlisted in `the test group` membership. but, if you look into the **maria2.docker**
![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/9e5915aa-3ac7-4b5a-a3df-8ebaf0ff47c9)

the new record is added to the corresponding table.

**Comment by navid-shokri** [comment]
:information_source: 
So, I will add Marie to the `Test group`: 
![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/2a888f6c-bc63-4298-8f61-2c73a157e757)
:tada: 
So as expected Marie will be notified about the new incoming share:

![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/02269272-11b5-4c69-b271-7181d8a50bf1)

**Comment by navid-shokri** [comment]
:information_source: 
and I will share the `shell` file with Marie  when she is a member of the **test group**
![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/d2a1a64f-c8ea-42a2-884d-fd133f1c5b95)

and she is notified directly without any problem:
![image](https://github.com/SURFnet/rd-sram-integration/assets/123634558/59e9c5aa-5be8-4b5f-9c49-b4416a43c3d3)

**Comment by michielbdejong** [comment]
Ah right! I had forgotten about https://github.com/pondersource/dev-stock/blob/main/scripts/testing-rd-sram.sh#L98-L99 - thanks!
