### ISSUE TITLE
Create new share types

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#43]
See https://github.com/owncloud/core/compare/master...pondersource:core:accept-ocm-to-groups#diff-816ea2f2c7ff9c5317a434c310eaf5c6208e86b3756e4b2ca65ddb7d71cb4951

@navid-dada I was wondering, would share type 6 still be used for anything, or would all existing remote shares change from type 6 to type 8?

**Comment by navid-dada** [comment]
I do not think that it can be feasible to just use a remote. because according to the notification class:

https://github.com/pondersource/core/blob/353925dfd56f050ffe5fb5cc9f538760e629af1d/apps/federatedfilesharing/lib/Notifications.php#L411

it is sending 'user_type' constantly. so we should have a flag to check that that selected recipient is a group or user. also as I checked in the NextCloud they are separating the contact by these two different remote types.

https://github.com/SURFnet/rd-sram-integration/issues/36#issuecomment-1357292217

**Comment by michielbdejong** [comment]
Sounds good! And would share type 6 still be used for anything, or would all existing remote shares change from type 6 to type 8?

**Comment by michielbdejong** [comment]
Look at https://github.com/pondersource/core/blob/5c912595af0dca9db6aa6b9dcc3f57dc9b699a0d/lib/private/Share/Constants.php#L28-L35

**Comment by navid-dada** [comment]
Ok, the discussion was convincing so I remove SHARE_REMOTE_USER from the core.
