### ISSUE TITLE
Why should we do an API call from the FederatedFileSharing app to the FederatedGroups app?

### ISSUE THREAD

**Issue by navid-dada** [SURFnet/rd-sram-integration#45]
As I understand from reviewing the changes in this diff page: 
https://github.com/owncloud/core/compare/master...pondersource:core:accept-ocm-to-groups

we are trying to make an API call from the FederatedFileSharing app to the FederatedGroup app. i.e we are routing incoming HTTP calls to another application. Why didn't we use a function call instead of an API call?

**Comment by michielbdejong** [comment]
It's because the controller is already [specific to receiving OCM shares to a user](https://github.com/pondersource/core/blob/ea6c9540d3f791264a6ce180c2e20ddaac5ecf00/apps/federatedfilesharing/lib/Controller/OcmController.php#L474-L481) and we were asked to copy-and-tweak.

We could rename 'OcmController' to 'OcmHelper' or 'OcmManager' but I think that would not make it clearer. If we would change the way its constructor works (e.g. with dependency injection instead of with `$this->request`) then I think that would be quite a bit of work and it would not really help us.
