### ISSUE TITLE
Take into account `'files_sharing', 'auto_accept_share'` config value

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#53]
As a stretch goal, we could improve ownCloud's behaviour so that the `'files_sharing', 'auto_accept_share'` config value also affects incoming OCM shares. Currently, as we saw in https://github.com/SURFnet/rd-sram-integration/issues/47#issuecomment-1367899123 it doesn't, and we chose to copy the behaviour for incoming OCM share to group from the behaviour for incoming OCM share to user, but it still feels a bit weird, so documenting this as a stretch goal.

**Comment by michielbdejong** [comment]
Sorry, related to 205, not to 207.

**Comment by soltanireza65** [comment]
@michielbdejong  or @navid-shokri 
do you mean this section in the admin setting???
![image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/6c9797c0-f33d-4386-a0c1-e649cbaf81ab)

**Comment by soltanireza65** [comment]
if so, there is a config value called `auto_accept_trusted` in `oc_appconfig;` table

**Comment by shokri-navid** [comment]
Yes, there is but we did not check that value on our OCM application

**Comment by soltanireza65** [comment]
![image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/6d6496a7-27a8-4f91-afea-30022e56f98a)

![image](https://github.com/SURFnet/rd-sram-integration/assets/53468377/6af0b189-976b-434f-a78a-aa461eff9e85)

**Comment by soltanireza65** [comment]
and it's also same for the remote group share

**Comment by soltanireza65** [comment]
o wait
previously we were creating share records for each member of a remote group
but now we are inserting just one record for the group and showing popups  for users who have not been accepted or declined the share before
first solution:
- inject into files-sharing and check if `auto_accept_trusted` is set to `True` for a member or not, if so we can insert one share record with the accepted flag set to `True` (requires a PR in core)

**Comment by navid-shokri** [comment]
I found some things.
So It seems we are trying to create the mount point for our group instead of user ❗ ❗ ❗

**Comment by soltanireza65** [comment]
first of all, next cloud has not this feature at all
but I have checked multiple solutions:

- check if `auto_accept_trusted` is set to 'yes' insert shares to all members with absolute mountPoints and the result was an error because we can not setup file system for non-logged-in users so `\OC_Util::setupFS($user);` will return false
- check if `auto_accept_trusted` is set to 'yes' insert shares to all members with temp mountPoints and then try to accept them and reset the mountPoint again the result was the same
- check if `auto_accept_trusted` is set to 'yes' and when a user tries to get the files try to accept shares fo the current user: this one worked 50% (we can accept/Insert the share, but the problem is that the files are showing before with dav in XML) 

so as a result whether we need to ignore it because nextcloud has no this feature, or setup an event(something like userLogedInEvent) and then accept the shares when the event fires

**Comment by soltanireza65** [comment]
https://github.com/pondersource/oc-opencloudmesh/pull/39
