### ISSUE TITLE
Implement resharing preshared files for OCM remote group.

### ISSUE THREAD

**Issue by navid-shokri** [SURFnet/rd-sram-integration#76]

**Comment by soltanireza65** [comment]
when we reshare a user-to-user shared file, it gets this response
```json
{
	"ocs": {
		"meta": {
			"status": "failure",
			"statuscode": 403,
			"message": "File is already shared with reza@oc1.docker",
			"totalitems": "",
			"itemsperpage": ""
		},
		"data": []
	}
}
```
indicating that the file is already being shared.
but actually, the file is sharing successfully
we should refactor the response in this case in believe.

**Comment by soltanireza65** [comment]
user to group share doesn't have any response.
share a file as user einstein in oc1 with helpdesk@oc2.docker

**Comment by soltanireza65** [comment]
- logged in as einstein in oc1.docker
- Share a file with reza@oc1.docker
- loged in as reza in oc1.docker
- accept share from einstein
- reshare the same file with navid@oc1.docker

this is the response
```json
{
	"ocs": {
		"meta": {
			"status": "failure",
			"statuscode": 403,
			"message": "File is already shared with navid@oc1.docker",
			"totalitems": "",
			"itemsperpage": ""
		},
		"data": []
	}
}
```

and these are the states of the oc_share_external table before and after resharing:

before resharing with navid@oc1.docker
![Screen Shot 2023-02-15 at 11 05 49 AM](https://user-images.githubusercontent.com/53468377/218964525-127c49ce-c1ee-46ef-aa1c-20d2df3d75d5.png)


after resharing with navid@oc1.docker
![Screen Shot 2023-02-15 at 11 12 32 AM](https://user-images.githubusercontent.com/53468377/218964573-34f23840-9f8f-48d9-8b71-12634757b657.png)

**Comment by michielbdejong** [comment]
OK, so two observations:
* it's weird that it allows you to share to a user at the same host, but maybe that is because the server doesn't know that "oc1.docker" is its own name. So let's not worry too much about that.
* It looks like the share from reza to navid is created successfully, so probably it's trying to do this twice; the first time it's successful and the second time it's not.

To make this easier to debug I would suggest sharing einstein@oc1.docker -> marie@oc2.docker -> navid@oc1.docker and see if that has the same behaviour.

Then you need to see if there are 1 or 2 OCM calls. It could be that:
A) marie@oc2.docker is sending out 2 OCM calls (the second one unsuccessful), or
B) marie@oc2.docker is sending out just 1 OCM call, but maybe there is a return statement missing somewhere, causing the code for adding the incoming share into the database to be executed twice on oc1.docker (the second one unsuccessful).

Try to find out whether it is A) or B) and then you can dig further from there!

**Comment by soltanireza65** [comment]
tested the  requested flow
and again result is the same as before.

**Comment by soltanireza65** [comment]
<img width="1030" alt="Screen Shot 2023-02-15 at 2 52 53 PM" src="https://user-images.githubusercontent.com/53468377/219014230-3e1b335c-8866-4f42-a891-e4c0a411147b.png">

**Comment by soltanireza65** [comment]
```json
{
    "reqId": "K59HlRJw6dsiTczty3EG",
    "level": 3,
    "time": "2023-02-15T11:17:35+00:00",
    "remoteAddr": "172.18.0.6",
    "user": "marie",
    "app": "PHP",
    "method": "POST",
    "url": "\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json",
    "message": "Undefined variable: send at \/var\/www\/html\/apps\/federatedfilesharing\/lib\/FederatedShareProvider.php#196"
}
```

**Comment by soltanireza65** [comment]
an INTERNAL_SERVER_ERROR is throwing in:
[/core/apps/federatedFileSharing/lib/Notifications.php](https://github.com/pondersource/core/blob/dfbbdce792546ed86aa8b747856abd95e260bacb/apps/federatedfilesharing/lib/Notifications.php#L380)

**Comment by soltanireza65** [comment]
this is the flow:
Share20OcsController:createShare asking share20Manager to create a share
The manager asking FederatedShareProvider to create the share
FederatedShareProvider calling askOwnerToReShare() "this is where the issue began"
calling Notification service to requestReShare (it must return a token)

and finally, the line that throws the errors :
`$result = $this->tryHttpPostToShareEndpoint($url, '/notifications', $ocmFields, true);
`https://github.com/pondersource/core/blob/dfbbdce792546ed86aa8b747856abd95e260bacb/apps/federatedfilesharing/lib/Notifications.php#L159

**Comment by soltanireza65** [comment]
Server error: `POST https://oc1.docker/index.php/apps/federatedfilesharing/notifications` resulted in a `500 Internal Server Error` response:\n<!DOCTYPE html>\n<html class="ng-csp" data-placeholder-focus="false" lang="en" >\n\t<head data-requesttoken="">\n\t\t<meta cha (truncated...)\n

**Comment by soltanireza65** [comment]
```json
{
    "reqId": "fuatOaj6PdW76dNbyg8e",
    "level": 3,
    "time": "2023-02-21T17:57:29+00:00",
    "remoteAddr": "172.18.0.4",
    "user": "--",
    "app": "index",
    "method": "POST",
    "url": "\/index.php\/apps\/federatedfilesharing\/notifications",
    "message": "Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC\\\\Share20\\\\Share::getType()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/Controller\\\/OcmController.php(364): OCA\\\\FederatedGroups\\\\FederatedFileSharing\\\\FedShareManager->reShare()\\n#1 \\\/var\\\/www\\\/html\\\/apps\\\/federatedfilesharing\\\/lib\\\/Controller\\\/OcmController.php(313): OCA\\\\FederatedGroups\\\\Controller\\\\OcmController->processNotification()\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(169): OCA\\\\FederatedFileSharing\\\\Controller\\\\OcmController->processNotification()\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(344): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(913): OC\\\\Route\\\\Router->match()\\n#8 \\\/var\\\/www\\\/html\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/rd-sram-integration\\\/federatedgroups\\\/lib\\\/FederatedFileSharing\\\/FedShareManager.php\",\"Line\":256}"
}
```

**Comment by soltanireza65** [comment]
Share object that we pass into FedShareManager->reShare
does not have a method called getType
there is a method called getShareType [decide if its the method to call or if we have to implement another]
 
![image](https://user-images.githubusercontent.com/53468377/220428562-741d33f5-3845-42b9-b00f-f6e61140614d.png)

anyway, the getShareType method is returning 6 as an integer and that's why 
getProviderForOcmShareType is throwing the error Unsupported share type 6

![image](https://user-images.githubusercontent.com/53468377/220429341-0b8abbf2-62af-4174-9a2d-f07b4ae15ed9.png)

**Comment by soltanireza65** [comment]
the idea is whether we have a type mismatch (and it's just a 'user' instead of 6),
or it should return a completely different Provider for this type

**Comment by soltanireza65** [comment]
It is fixed and tested in https://github.com/SURFnet/rd-sram-integration/pull/107 
tested scenario: 

1. log in to oc1.docker einstein
2. share a file with marie@oc2.docker
3. login to oc2.docker marie
4. accept share from einstein
5. reshare the same file with reza@oc1.docker 
6. login to oc1.docker reza
7. accept reshared file

**Comment by soltanireza65** [comment]
@navid-shokri 
please give a comment
